export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCEED = 'REQUEST_SUCCEED';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const SET_BUCKETS = 'SET_BUCKETS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
